### PR TITLE
Club recordings page

### PR DESCRIPTION
**Pull request by prithvidiamond1**
Implement what we agreed on for the club recordings page which includes:

- Having a single Youtube playlist embed.
- Ditching the redundant side navbar

I also fixed the positioning for some elements like the footer.

Here is a preview of how it looks:
image

Note: The playlist displayed currently is just a random playlist from the DevilSec channel, someone from the content/education team has to give us the link to the actual playlist that needs to be displayed here.

### CODE REVIEW

**Review by daylamtayari — CHANGES_REQUESTED** [review]
When talking about having the recordings page a playlist embed in the meeting, we meant a list of videos on one side and then one of the recordings (or the latest video) is embedded on the main part as you already have done.
So if you could add the list of videos from the YouTube playlist on the side that would be much appreciated.

**Comment by prithvidiamond1** [comment]
> When talking about having the recordings page a playlist embed in the meeting, we meant a list of videos on one side and then one of the recordings (or the latest video) is embedded on the main part as you already have done. So if you could add the list of videos from the YouTube playlist on the side that would be much appreciated.
> 
> Also please remove the edits made in the `GetConnected.html` file, Ben has already taken care of them on his end and pushed it.

Alright, I will get rid of the edits in the GetConnected file.

About the playlist, it does have a list of videos from the playlist but it doesn't actively show them. There is a button in the top right corner of the embed which shows the list of videos when you click it. However and as far as I have searched, there seems to be no way to make it appear actively as Youtube's iFrame embed's don't support such a thing.

If you still want such functionality, it may be possible with other javascript plugins and stuff but it will definitely involve quite a bit of work to get it sorted.

**Review by prithvidiamond1 — COMMENTED** [review]
Reverted the changes in `GetConnected.html`. Waiting for a response about the playlist thing.

**Review by daylamtayari — APPROVED** [review]
Matches specification requested and no issues visible.

**Review by KyleMuncie — APPROVED** [review]
Approved

**Pull request merged**
