### PR TITLE
Commit 3:

### PR DESCRIPTION
**Pull request by KyleMuncie**
*Created the base layout of the home page
*Changed the DSSchedule to show active when on that current page

### CODE REVIEW

**Comment by daylamtayari** [comment]
I'm not really a fan of the design but will clarify that up and talk about it at the next meeting.
I think round corners with a thin border around it which slightly expands and changes to maroon when highlighted would look much better.

**Comment by daylamtayari** [comment]
I'll prepare a mockup of what I'm talking about for the next meeting and then we can discuss it with all team members present too.

**Review by daylamtayari — APPROVED** [review]
No issues with the code or display, approving.

**Comment by KyleMuncie** [comment]
I am unable to Review this because I made the pull request. Unless I'm doing something wrong.

**Pull request merged**
